# -*- coding: utf-8 -*-
"""Book recommendation system

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oGNKPkPaI2UZRyG8MY8JVJaupTQthGB_
"""

#Description: Build a book recommendation engine/system

#Import the libraries
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

#Load the data
from google.colab import files
files.upload()

#Store the data
df = pd.read_csv('data.csv', encoding = 'unicode_escape', on_bad_lines = 'skip')

#Show the data
df

df.info()

#Find duplicates
df.duplicated(subset='title').sum()

#Remove duplicates
df = df.drop_duplicates(subset = 'title')

#Create a list of columns to keep
column = ['title','authors','categories']

#Re running the code to check for duplicates
df.duplicated(subset='title').sum()

#Random sampling to avoid memory erros
sample_size = 5000
df = df.sample(n = sample_size, replace=False, random_state=430)
df = df.reset_index() #resets the index of the DataFrame df to the default integer index
df = df.drop('index',axis = 1) #removes index column, axis = 1(column) and 0(row)

#Cleaning the data
#Combining author's first and last name for CountVectorizer
def clean_text(author):
  result = str(author).lower()
  return result.replace(" ","")

df['authors'] = df['authors'].apply(clean_text)
df

#Converting book title and genre/categories to lowercase
df['title'] = df['title'].str.lower()
df['categories'] = df['categories'].str.lower()
df

#Combine all strings
df2 = df.drop(['isbn13','isbn10','subtitle','thumbnail',	'description',
               'published_year', 'average_rating', 'num_pages',	'ratings_count'], axis = 1)

df2['data'] = df2[df2.columns[1: ]].apply(lambda x: ' '.join(x.dropna().astype(str)), axis = 1)
print(df2['data'].head())

#Vectorizing the dataframe
vectorizer = CountVectorizer()
vectorized = vectorizer.fit_transform(df2['data'])

#Using cosine similarity to get similarities
similarities = cosine_similarity(vectorized)
print(similarities)

#Converting the similarity vectors into a dataframe
df = pd.DataFrame(similarities, columns=df['title'], index=df['title']).reset_index()

#Randomly picking a book and giving five recomendations related to that book
import random
book_titles = list(df['title'])
input_book =  random.choice(book_titles)
print(f"Book recommendations for {input_book.title()}")
recommendations = pd.DataFrame(df.nlargest(6, input_book)['title'])
recommendations = recommendations[recommendations['title']!=input_book]
print(recommendations)